### ISSUE TITLE
Consider automated Google setup

### ISSUE THREAD

**Issue by gedw99** [cameronkinsella/manga-translator#2]
I had lots of troubles getting all the service account and keys setup yesterday manually. You explained it pretty well in the readme, but i still went nuts trying to second guess in via the Google console gui.
I still have not gotten all the config correct.  Google Vision works but not Google Translator

So perhaps this might be work using ?

https://github.com/caos/orbos

**Comment by gedw99** [comment]
I did not explain it so well i think.

Currently you have a nice cmd/manga-translator-setup walk through for the user.

If this can also call gcloud to do the things that your normally need to do via the google web console it would make it make it easier to get going.

Also manga-translator-setup is idempotent, in that you can run it again and again, and with gcloud cli, it is also possible to be idempotent, so it is a good marriage.

**Comment by cameronkinsella** [comment]
Good idea. I would like to keep `cmd/manga-translator-setup` as it is since it has no external dependencies. However, I will work on adding a separate script for automatically creating/enabling the necessary gcloud resources with the gcloud CLI when I get the chance.

**Comment by gedw99** [comment]
Thanks. Less deps the better.

**Comment by cameronkinsella** [comment]
A bit of a long wait, but I just pushed some changes to the README in [1.3.0](https://github.com/cameronkinsella/manga-translator/releases/tag/1.3.0) that should make getting started a lot easier. 🎉

**Comment by gedw99** [comment]
@cameronkinsella wil give it a try...
