### ISSUE TITLE
Incorrect recognition boxes

### ISSUE THREAD

**Issue by jusjla** [cameronkinsella/manga-translator#3]
On several manga that I am working to translate, the boxes which cover the translated text appear to not be capturing the entire speech buble and as such is producing nonsense translations. Would there be a way to manually create these boxes around the text so it knows which exact characters to try and translate or is this a limitation of the OCR software?

**Comment by cameronkinsella** [comment]
As of right now, that is not possible to do. However, I believe I may implement such a function in the future. For now, I suggest one of the following workarounds:

1. It's a hassle, but you can manually crop the image to the block of text you want to translate.
2. You can try something like [capture2text](http://capture2text.sourceforge.net/). The OCR is not quite as accurate, but you can manually select portions of your screen to capture. (I'm not affiliated with them, but I personally use it and find it helpful)

**Comment by cameronkinsella** [comment]
Added a new option to translate an image from your clipboard. Use the Windows snipping tool (Windows key + Shift + S) to manually select the area you want to translate then launch the application with the clipboard option.

Hope that helps 👍
