### ISSUE TITLE
Issue with cloud shell commands

### ISSUE THREAD

**Issue by JordiSucciGirl** [cameronkinsella/manga-translator#6]
josselynennie@cloudshell:~$ cloudshell_open --repo_url "https://github.com/cameronkinsella/manga-translator" --page "editor" --open_in_editor "scripts/cloudshell/create-service-account-key.md" --force_new_clone
2022/10/14 21:36:54 Cloning https://github.com/cameronkinsella/manga-translator into /home/josselynennie/cloudshell_open/manga-translator
Cloning into '/home/josselynennie/cloudshell_open/manga-translator'...
remote: Enumerating objects: 372, done.
remote: Counting objects: 100% (17/17), done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 372 (delta 8), reused 5 (delta 5), pack-reused 355Receiving objects: 100% (372/372), 4.45 MiB | 26.18 MiB/s, done.
Resolving deltas: 100% (191/191), done.
Traceback (most recent call last):
  File "/usr/local/bin/cloudshell", line 496, in <module>
    main()
  File "/usr/local/bin/cloudshell", line 493, in main
    args.handler(args)
  File "/usr/local/bin/cloudshell", line 110, in edit_files
    open(filename, 'a').close()
FileNotFoundError: [Errno 2] No such file or directory: '/home/josselynennie/cloudshell_open/manga-translator/scripts/cloudshell/create-service-account-key.md'

**Comment by JordiSucciGirl** [comment]
That's getting the first api key generated

**Comment by cameronkinsella** [comment]
Thank you for submitting this issue, the problem should now be fixed. Please try pressing the "Open in Google Cloud Shell" button in the [README](https://github.com/cameronkinsella/manga-translator#google-cloud-vision-api) again.
