### ISSUE TITLE
Cannot download images 

### ISSUE THREAD

**Issue by Its-Arslan** [cameronkinsella/manga-translator#7]
Im trying to translate manhua by putting this (https://rawkuma.com/) site link but its say cannot download images.plss fix this!
[Screenshot_2022-11-01-03-04-04-344_com.wiryaimd.mangatranslator.jpg](https://user-images.githubusercontent.com/61835791/199119276-d53dd0b4-3a86-498b-b115-d65b06d34721.jpg)

**Comment by cameronkinsella** [comment]
Hey, it looks like you're in the wrong place. The manga translator app that you showed in your screenshot is not mine. ☹️
